CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_PHONE VARCHAR2(13) NOT NULL,
    MEMBER_EMAIL VARCHAR2(30) NOT NULL
);
CREATE TABLE PRODUCT(
     PRODUCT_NAME VARCHAR2(20) PRIMARY KEY,
     PRODUCT_PRICE NUMBER NOT NULL,
     PRODUCT_COUNT NUMBER NOT NULL
);
INSERT INTO MEMBER VALUES('admin', 'admin', '박상은', '01012341234', 'asd@naver.com');

INSERT INTO PRODUCT VALUES('빵1',3500,3);
INSERT INTO PRODUCT VALUES('빵2',1500,8);
INSERT INTO PRODUCT VALUES('빵3',2500,5);
COMMIT;
